server.port=8080

# Classroom Bedrock API key
classroom.apiKey=-nYStsHhqf7vI4dNCPwnm1UFiPMwTTNCT2CMppOYcMc

# File upload limit
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
